export interface Environment
{
	production: boolean;
	
	SERVICES_ENDPOINT: string;
	HTTPS_SERVICES_ENDPOINT: string;
	GQL_ENDPOINT: string;
	GQL_SUBSCRIPTIONS_ENDPOINT: string;
	
	APP_VERSION: string;
	
	CLOUDINARY_SIGNED_UPLOAD_PRESET: string;
	CLOUDINARY_UNSIGNED_UPLOAD_PRESET: string;
	CLOUDINARY_UPLOAD_URL: string;
	API_FILE_UPLOAD_URL: string;
	
	FAKE_MERCHANT_NAME: string;
	FAKE_MERCHANT_PASSWORD: string;
	FAKE_MERCHANT_EMAIL: string;
	
	DEFAULT_COORDINATES: boolean;
	DEFAULT_LATITUDE: number;
	DEFAULT_LONGITUDE: number;
	
	LOGIN_LOGO: string;
	NO_INTERNET_LOGO: string;
	
	COMPANY_NAME: string;
	APP_NAME: string;
	
	GOOGLE_MAPS_API_KEY: string;
	
	TALKJS_APP_ID: string;
	
	GOOGLE_ANALYTICS_API_KEY: string;
	FAKE_UUID: string;
	MIXPANEL_API_KEY: string;
	
	WAREHOUSE_PASSWORD_BCRYPT_SALT_ROUNDS: number;
	
	MAP_MERCHANT_ICON_LINK: string;
	
	MAP_USER_ICON_LINK: string;
	
	MAP_CARRIER_ICON_LINK: string;
	
	DEFAULT_LANGUAGE: string;
	AVAILABLE_LOCALES: string;
	
	// For maintenance micro service
	SETTINGS_APP_TYPE: string;
	SETTINGS_MAINTENANCE_API_URL: string;
}
