version: '3.7'

services:
    mongo:
        image: mongo
        container_name: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - mongo_data:/data/db
        command: mongod --logpath=/dev/null # --quiet
        networks:
            - overlay
    
    #    carrier-mobile:
    #        container_name: carrier-mobile
    #        image: emarket-carrier-mobile:latest
    #        command: yarn run:carrier
    #        build:
    #            context: .
    #            dockerfile: .docker/carrier-mobile-ionic/Dockerfile
    #        environment:
    #            NODE_ENV: production
    #        restart: on-failure
    #        depends_on:
    #            - core
    #        ports:
    #            - "4203:4200"
    #            - "4204:4203"
    #        networks:
    #            - overlay
    
    #    shop-mobile:
    #        container_name: shop-mobile
    #        image: emarket-shop-mobile:latest
    #        command: yarn run:shopmobile
    #        build:
    #            context: .
    #            dockerfile: .docker/shop-mobile-ionic/Dockerfile
    #        environment:
    #            NODE_ENV: production
    #        restart: on-failure
    #        depends_on:
    #            - core
    #        ports:
    #            - "4201:4201"
    #        networks:
    #            - overlay
    
    merchant-mobile:
        container_name: merchant-mobile
        image: emarket-merchant-mobile:latest
        command: yarn run:merchant
        build:
            context: .
            dockerfile: .docker/merchant-tablet-ionic/Dockerfile
        environment:
            NODE_ENV: production
        restart: on-failure
        depends_on:
            - core
        ports:
            - "4202:4202"
        networks:
            - overlay
    
    admin-web:
        container_name: admin-web
        image: emarket-admin-web:latest
        command: yarn run:admin
        build:
            context: .
            dockerfile: .docker/admin-web-angular/Dockerfile
        environment:
            NODE_ENV: production
        restart: on-failure
        depends_on:
            - core
        ports:
            - "4200:4200"
        networks:
            - overlay
    
    shop-web:
        container_name: shop-web
        image: emarket-shop-web:latest
        command: yarn run:shopweb
        build:
            context: .
            dockerfile: .docker/shop-web-angular/Dockerfile
        environment:
            NODE_ENV: production
        restart: on-failure
        depends_on:
            - core
        ports:
            - "8080:8080"
        expose:
            - 8080
        networks:
            - overlay
    
    core:
        container_name: core
        image: emarket-core:latest
        build:
            context: .
            dockerfile: .docker/core/Dockerfile
        environment:
            NODE_ENV: production
            WAIT_HOSTS: mongo:27017
            DB_URI: mongodb://mongo/emarket
            TESTING_DB_URI: mongodb://mongo/emarket_test
        restart: on-failure
        depends_on:
            - mongo
        links:
            - mongo
        volumes:
            - .:/home/emarket
            - root_node_modules:/home/emarket/node_modules
            - core_node_modules:/home/emarket/packages/core/node_modules
        ports:
            - "5500:5500"
            - "5501:5501"
            - "5050:5050"
            - "5555:5555"
        networks:
            - overlay

volumes:
    root_node_modules:
    core_node_modules:
    certificates:
    mongo_data:

networks:
    overlay:
        driver: bridge
