import { readdirSync, readFileSync, unlinkSync, writeFile } from 'fs';
import * as path                                            from "path";

const headerComment = "// Autogenerated file: File contents are read from\n"
                      + "// common/src/i18n folder files.\n"
                      + "// To add translation add json to mentioned folder";

function readDirContent(relPath: string): string[]
{
	return readdirSync(path.resolve(__dirname, relPath));
}

function readFileContent(relPath: string): string
{
	return readFileSync(
			path.resolve(__dirname, relPath), { encoding: 'utf8' }
	);
}

export function getCountries()
{
	const relPath = '../src/i18n/countries';
	let i18nFiles = readDirContent(relPath);
	let countries: string = "{";
	
	i18nFiles.forEach((file, index) =>
	                  {
		                  let content = readFileContent(`${relPath}/${file}`);
		                  content = content.slice(1, content.length - 2);
		
		                  if(content.endsWith("\n"))
		                  {
			                  content = content.slice(0, content.length - 1);
		                  }
		
		                  countries += (index < i18nFiles.length - 1)
		                               ? content + ","
		                               : content;
	                  })
	
	countries += "\n}";
	return countries;
}

export function getLanguages()
{
	const relPath = '../src/i18n/languages.json';
	let languages = readFileContent(relPath);
	
	if(languages.endsWith("\n"))
	{
		languages = languages.slice(0, languages.length - 1);
	}
	
	return languages;
}

const countriesFileContent = `${headerComment}

export const COUNTRIES = ${getCountries()};
`;

const languagesFileContent = `${headerComment}

export const LANGUAGES = ${getLanguages()};
`;

const countriesDest: string = './src/data/countries.ts';
const languagesDest: string = './src/data/languages.ts';

try
{
	unlinkSync(countriesDest);
	unlinkSync(languagesDest);
} catch
{}

writeFile(
		countriesDest,
		countriesFileContent,
		(err) =>
		{
			if(err)
			{
				console.log(err);
			}
			else
			{
				console.log(`Generated countries file: ${countriesDest}`);
			}
		});

writeFile(
		languagesDest,
		languagesFileContent,
		(err) =>
		{
			if(err)
			{
				console.log(err);
			}
			else
			{
				console.log(`Generated languages file: ${languagesDest}`);
			}
		});
