import { readdirSync, readFileSync, unlinkSync, writeFile } from 'fs';
import * as path                                            from "path";

export function getCountries()
{
	let i18nContent = readdirSync(path.resolve(__dirname, '../src/i18n'));
	
	let countries: string = "{";
	
	i18nContent.forEach((file, index) =>
	                    {
		                    let content = readFileSync(
				                    path.resolve(__dirname, `../src/i18n/${file}`),
				                    { encoding: 'utf8' }
		                    );
		                    content = content.slice(1, content.length - 2)
		                    countries += (index < i18nContent.length - 1)
		                                 ? content + ','
		                                 : content;
	                    })
	
	countries += "}"
	return countries;
}

const countriesFileContent = `
// Autogenerated file: File contents are read from\n
// common/src/i18n folder files.\n
// To add translation add json to mentioned folder \n
export const COUNTRIES = ${getCountries()}
`;

const fileDest: string = './src/data/countries.ts';

try
{
	unlinkSync(fileDest);
} catch
{}

writeFile(fileDest, countriesFileContent, function(
		err
)
{
	if(err)
	{
		console.log(err);
	}
	else
	{
		console.log(`Generated countries file: ${fileDest}`);
	}
});
